### ISSUE TITLE
Occasional crashes in Qt code

### ISSUE THREAD

**Issue by wm4** [cmdrkotori/mpc-qt#31]
I can't tell if this is a mpc-qt specific issue - it might not.

It seems to crash sometimes here: https://github.com/qtproject/qtbase/blob/5.5/src/gui/kernel/qopenglcontext.cpp#L713

The cause is unclear, and it happens randomly, maybe 1 or 2 times a week.

Here's a backtrace (no symbols, sorry):
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6f7ea54 in QOpenGLContext::functions() const ()
   from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
(gdb) bt
#0  0x00007ffff6f7ea54 in QOpenGLContext::functions() const ()
   from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#1  0x00007ffff755bcd2 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#2  0x00007ffff755c270 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#3  0x00007ffff753cf28 in QWidget::event(QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#4  0x00007ffff74f9ffc in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#5  0x00007ffff74ff4b6 in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#6  0x00007ffff6c075ab in QCoreApplication::notifyInternal(QObject*, QEvent*)
    () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007ffff7535a19 in QWidgetPrivate::sendPaintEvent(QRegion const&) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#8  0x00007ffff7536061 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#9  0x00007ffff7536d0c in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#10 0x00007ffff7536bf9 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, ---Type <return> to continue, or q <return> to quit---
QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00007ffff7535bd1 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007ffff7536d0c in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007ffff7535bd1 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007ffff7536d0c in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007ffff7536bf9 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007ffff7536bf9 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007ffff7535bd1 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
---Type <return> to continue, or q <return> to quit---
#18 0x00007ffff7536d0c in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x00007ffff7535bd1 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007ffff750784a in ?? ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007ffff7507a2c in ?? ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007ffff7525bbf in QWidgetPrivate::syncBackingStore() ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007ffff753cd28 in QWidget::event(QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007ffff7652c3b in QMainWindow::event(QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#25 0x00007ffff74f9ffc in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#26 0x00007ffff74ff4b6 in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#27 0x00007ffff6c075ab in QCoreApplication::notifyInternal(QObject*, QEvent*)
    () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#28 0x00007ffff6c099a6 in QCoreApplicationPrivate::sendPostedEvents(QObject*, in---Type <return> to continue, or q <return> to quit---
t, QThreadData*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#29 0x00007ffff6c5d633 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#30 0x00007fffed20d1a7 in g_main_context_dispatch ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#31 0x00007fffed20d400 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#32 0x00007fffed20d4ac in g_main_context_iteration ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#33 0x00007ffff6c5da3f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#34 0x00007ffff6c04d6a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#35 0x00007ffff6c0ce0c in QCoreApplication::exec() ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#36 0x000000000042271a in Flow::run() ()
#37 0x000000000041c0af in main ()
```

I have no idea how this could be analyzed. I'm trying running with Qt 5.6 now.

**Comment by cmdrkotori** [comment]
Looks like a bug that occurs with syncing the backing store. In any case, I've removed the requests (63c0a18) for non-native widgets because losing the viewport no longer occurs without them. So maybe mpc-qt will stop being a special snowflake.

Please let me know if it fixed the bug. I can also try directly asking for a gl surface, but I will for sure feel like I'd be shooting in the dark.

**Comment by wm4** [comment]
So far it hasn't happened again.

**Comment by cmdrkotori** [comment]
Ok, thanks.

**Comment by wm4** [comment]
I have to add that sometimes, the UI still gets messed up when switching to mpc-qt. This may or may not be related to the crash or its fix. Symptoms include:

- mpc-qt logo not drawn correctly, black screen instead
- cover art not drawn correctly, black screen instead
- garbage (like uninitialized memory) instead of logo or cover art
- corrupted rendering of the progress bar GUI element

It fixes itself when forcing mpc-qt to somehow redraw.

I don't know what to make of this, I just thought I'd let you know.

**Comment by wm4** [comment]
Well, haven't seen the originally reported crash since then.
